CREATE TABLE IF NOT EXISTS marketplace_txs_raw (
    blockNumber INT,
    timeStamp INT,
    hash TEXT PRIMARY KEY,
    nonce INT,
    blockHash TEXT,
    transactionIndex REAL,
    from_wallet TEXT,
    to_wallet TEXT,
    tx_value REAL,
    gas INT,
    gasPrice INT,
    isError INT,
    txreceipt_status INT,
    input TEXT,
    contractAddress TEXT,
    cumulativeGasUsed TEXT,
    gasUsed INT,
    confirmations INT
);